### ISSUE TITLE
What’s your take on adobo?

### ISSUE THREAD

**Issue by Kuugang** [Anato-Eini/Digital-Image-Processing#1]
What’s your take on adobo?
I’ve been wanting to master the art of cooking adobo (who doesn’t love a good adobo, right?) I’ve been trying out different methods in prepping but I feel like it still lacks something

please do share your adobo recipes and methods!

u/[And_Im_the_Devil](https://www.reddit.com/user/And_Im_the_Devil/) avatar
And_Im_the_Devil
•
[2y ago](https://www.reddit.com/r/filipinofood/comments/125tv40/comment/je7c4uz/)
•
A lot of people seem to do 2 parts soy sauce to 1 part vinegar. I like to do at least 1/1. Like others say, be generous with the garlic. There's something magical about the vinegar/garlic combo, and I don't like the saltiness of the soy sauce to completely overpower that feature. If I'm feeling particularly adventurous, I will do 2 parts vinegar to 1 part soy sauce.

Another thing I like to do is, when the chicken is cooked, take it out and put it under the broiler to crisp up the skin. Don't return the pieces to the sauce after that—put the chicken right onto a pile of rice, and then ladle your desired amount of sauce.

This may be blasphemous, but I usually don't bother with marinating as I find it doesn't make much of a difference. Whether I marinate for 20 mins, overnight, or not at all, it comes out the same in my experience. Your mileage may vary.

I say ditto to the other commenter who said to use whole peppercorns and to reduce your sauce.

Upvote
9

Downvote

Reply
reply

Award

Share
Share

**Comment by Momonan0412** [comment]
![Uploading anna-yanami-yanami-anna.gif…]()

**Comment by avrilnigelchua0412** [comment]
![anna-yanami-yanami-anna](https://github.com/user-attachments/assets/caea8407-b7e9-44f5-a6c3-dab197ed51a6)

**Comment by Xylphy** [comment]
HAHAHAHAHAHAHHAHAHHAHAHAHAHAHA
